; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = minima

; 공통 설정 — 모든 env에 자동 적용
[env]
platform = renesas-ra
framework = arduino
;monitor_speed = 115200
lib_deps =
    z3t0/IRremote@^4.7.1
    arduino-libraries/Ethernet@^2.0.2

; Arduino UNO R4 Minima
;   빌드/업로드: pio run -e minima -t upload
[env:minima]
board = uno_r4_minima

; Arduino UNO R4 WiFi
;   빌드/업로드: pio run -e wifi -t upload
[env:wifi]
board = uno_r4_wifi
